# Generated by Django 3.0.4 on 2021-09-11 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='utilities',
            fields=[
                ('fib_title', models.CharField(max_length=200)),
                ('fib_select', models.CharField(choices=[('24', '24 COUNT'), ('96', '96 COUNT'), ('144', '144 COUNT'), ('432', '432 COUNT'), ('864', '864 COUNT')], max_length=200)),
                ('in_seq', models.IntegerField(blank=True, null=True)),
                ('out_seq', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seq.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='seq.Tag'),
        ),
    ]
