# Generated by Django 3.0.4 on 2021-09-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0003_auto_20210912_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequentials',
            name='fiber_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seq.projects'),
        ),
    ]
