# Generated by Django 3.0.4 on 2021-11-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0006_projects_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequentials',
            name='project_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seq.projects'),
        ),
    ]
