# Generated by Django 3.0.4 on 2021-12-31 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0007_sequentials_project_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_images',
            fields=[
                ('image_title', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='project_images/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seq.projects')),
            ],
        ),
    ]
