# Generated by Django 3.0.4 on 2022-01-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0008_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tag',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
