# Generated by Django 3.0.4 on 2022-01-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0009_auto_20220101_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_images',
        ),
    ]
