# Generated by Django 3.0.4 on 2022-01-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0010_delete_project_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['id']},
        ),
    ]
