# Generated by Django 3.0.4 on 2021-09-12 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0002_auto_20210911_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiber',
            fields=[
                ('fib_title', models.CharField(max_length=200)),
                ('fib_select', models.CharField(choices=[('24', '24 COUNT'), ('96', '96 COUNT'), ('144', '144 COUNT'), ('432', '432 COUNT'), ('864', '864 COUNT')], max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sequentials',
            fields=[
                ('in_seq', models.IntegerField(blank=True, null=True)),
                ('out_seq', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fiber_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seq.fiber')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='project_relationship',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='utilities',
        ),
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.ManyToManyField(blank=True, to='seq.tags'),
        ),
        migrations.AddField(
            model_name='fiber',
            name='project_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seq.projects'),
        ),
    ]
